### ISSUE TITLE
[Raw Data] Evolution Methods Tracker

### ISSUE THREAD

**Issue by HoeenCoder** [HoeenCoder/SpacialGaze#74]
We have to manually write this, here's who's doing what:

- [x] Kanto: @Lord-Haji
- [x] Johto: @Karps-Soul
- [x] Hoenn: @Hirotto
- [x] Sinnoh: @Hirotto
- [x] Unova: @Hirotto 
- [x] Kalos: @Hirotto
- [x] Alola: @Karps-Soul
- [x] Alternate Formes: @HoeenCoder

Currently, no open spots are available. However, if one opens (it will be marked as **TBD**, either contact Mystifi/HoeenHero on the server or comment below.)

**Comment by Lord-Haji** [comment]
@Karps-Soul Hitmontop is bugged be sure to check it before PR

**Comment by Lord-Haji** [comment]
@HoeenCoder I though i'd start with Unova coz i have nothing to do all the day i would finish it.
But @Mystifi already took it feelsbd

**Comment by Lord-Haji** [comment]
Someone fix sigilyph @Karps-Soul @Hirotto I don't want to fix and steal ur diff

**Comment by Hirotto** [comment]
I'm at school rn i'll fix it in a couple of hours hopefully - HiroZ

Le 30 janv. 2017 08:45, "Executive Dronpes" <notifications@github.com> a
écrit :

**Comment by Polaris276** [comment]
Hitmon's family is gen1/gen2 and Sigilyph is gen 5.
I did gen 3/4/6

**Comment by Lord-Haji** [comment]
ok then @Karps-Soul shall do it

**Comment by HoeenCoder** [comment]
@Lord-Haji your JSON is screwed up you forgot a ton of `}`s

**Comment by HoeenCoder** [comment]
JSON needs cleaning so it works properly theres still some missing `}` from other areas.

**Comment by HoeenCoder** [comment]
@Mystifi hows Unova going?

**Comment by HoeenCoder** [comment]
On alternate formes: Were missing some pre-evos completely, add them if you do the alternate formes. Rate is the same as the rate for the non alola forme. num is the dex num.
